version: '3'
services:
    docker-node-network-mongo:
        image: ounes/djw
        ports:
            - "8080:8080"
        networks:
            - mongonet
    mongodev:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - mongonet
networks:
    mongonet:
        driver: bridge